### ISSUE TITLE
world time continues on

### ISSUE THREAD

**Issue by felix920506** [rexlNico/RealTimePlugin#7]
World time continues on after installing this plugin, only getting back in sync with server time once the sync interval comes.
Setting doDaylightCycle to False fixes it until server restarts

This didn't happen before updating from 1.17.1 to 1.18.2

Plugin version: 3.5
Server version: Purpur 1.18.2-1632
Previous Server version: Purpur 1.17.1-1428

**Comment by rexlNico** [comment]
Can't reproduce this error.

**Comment by rexlNico** [comment]
Can't reproduce this error.
